[package]
name = "roto_py_msgspec_backend_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roto_core = { path = "../roto_core" }